Check pyproject.toml before publishing a tag

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -7,9 +7,43 @@ on:
 
 jobs:
 
+  check_publish:
+    name: "Check if we should publish"
+    runs-on: ubuntu-latest
+    outputs:
+      result: ${{ steps.check_pyproject_toml.outputs.version_exit_code }}
+
+    steps:
+      - name: "Checkout repository"
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+        with:
+          fetch-depth: 0
+
+      - name: "Setup Python"
+        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
+        with:
+          python-version: "3.x"
+
+      - name: "Check pyproject.toml for a new version"
+        id: check_pyproject_toml
+        run: |
+          cd ./publish && echo "version_exit_code=$((python3 check_pyproject.py --tag ${{ github.ref_name }}) 2>&1)" >> $GITHUB_OUTPUT
+
+  fail_if_output_not_zero:
+    name: "Fail the job if the publish check doesn't return '0'"
+    runs-on: ubuntu-latest
+    needs: [ check_publish ]
+    if: needs.check_publish.outputs.result != '0'
+
+    steps:
+      - run: |
+          echo "Job failed, there is an issue with the tag; check that the version exists in pyproject and not in pypi" && exit 1
+
   build:
     name: "Build package"
     runs-on: ubuntu-latest
+    needs: [ check_publish ]
+    if: needs.check_publish.outputs.result == '0'
     outputs:
       hashes: ${{ steps.hash.outputs.hashes }}
 
@@ -61,7 +95,7 @@ jobs:
 
   publish-to-test-pypi:
     name: "Publish to Test PyPI"
-    needs: [ "build", "provenance" ]
+    needs: [ build, provenance ]
     permissions:
       id-token: write # Needed for trusted publishing to PyPI.
     runs-on: "ubuntu-latest"
@@ -84,7 +118,7 @@ jobs:
   publish-to-pypi:
     name: "Publish to PyPI"
     if: startsWith(github.ref, 'refs/tags/')
-    needs: [ "publish-to-test-pypi" ]
+    needs: [ publish-to-test-pypi ]
     permissions:
       contents: write # Needed for making GitHub releases
       id-token: write # Needed for trusted publishing to PyPI.
